title: "fibonhack"

# Build settings
markdown: kramdown

collections:
  authors:
    # By default, collections do not output a page for documents.
    # In this case we want each author to have their own page so
    # let’s tweak the collection configuration.
    permalink: /members/:title
    output: true
  main:
    permalink: /:path
    output: true
  writeups:
    permalink: /:path
    output: true
  ourposts:
    permalink: /:path
    output: true
  ourevents:
    permalink: /events/:path
    output: true
  logo:
    permalink: /:collection/:path
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: "writeup"
  - scope:
      path: ""
      type: "ourposts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "ourevents"
    values:
      layout: "event"


plugins:
  - jekyll-postcss

social:
  email: echo ti.kcahnobif@ofni|rev
  twitter: https://twitter.com/fibonhack
  github: https://github.com/fibonhack
  ctftime: https://ctftime.org/team/117538

exclude:
  - assets/css
  - docker-compose.yml
  - Dockerfile
  - package.json
  - package-lock.json
  - postcss.config.js
  - README
  - tailwind.config.js

sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]
