version: "2.0"

services:
  jekyll:
    build: .
    ports:
      - 4000:4000
    volumes:
      - ".:/srv/jekyll"

    working_dir: "/srv/jekyll"

    command: sh -c "npm install && JEKYLL_ENV=production NODE_ENV=production bundle exec jekyll serve --incremental --trace --host 0.0.0.0"
