on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install

    - name: Build the site
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/jekyll:latest /bin/bash -c "chmod -R 777 /srv/jekyll && bundle install && npm run build"

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site
