on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build -t tmp . && docker run --rm -v ${{ github.workspace }}/_site:/site/_site tmp npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
